### ISSUE TITLE
[Enhancement] Shield option

### ISSUE THREAD

**Issue by Aides123** [PurpurMC/PurpurExtras#15]
Hey, he suggests adding new settings to shield.
- When a player hits with an axe the shield gets a cooldown,
- You can set how long the cooldown lasts
- Possibility to set how much damage you want to receive when using a shield.

**Comment by YouHaveTrouble** [comment]
2/3 added [here](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.22.0). If the first point is still something you'd be interested in seeing, please open new issue for it
