### ISSUE TITLE
flying axolotls.

### ISSUE THREAD

**Issue by saboooor** [PurpurMC/PurpurExtras#30]
there is finally a place to suggest this, i reintroduce flying axolotls

**Comment by YouHaveTrouble** [comment]
I need context

**Comment by saboooor** [comment]
https://github.com/PurpurMC/Purpur/issues/390

**Comment by YouHaveTrouble** [comment]
That might be tricky, would probably require a lot of time and effort to make it work, if at all possible.
Feel free to PR maintainable solution if you have one tho.

**Comment by YouHaveTrouble** [comment]
A lot of time passed and I still have absolutely no idea how would that work. PRs are still welcome, but closing this issue, because it's kinda unrealistic to do and maintain to begin with
