### ISSUE TITLE
[Enhancement] Preserve NBT data when mobs are transformed by lightning

### ISSUE THREAD

**Issue by Keeg-Turner** [PurpurMC/PurpurExtras#37]
I'd imagine it'd take a lot of effort to properly handle the transfer every applicable NBT tag from one entity to another, so I'll just list the ones that seem the most important:
- Held items (main hand and off-hand)
- Armour slots
- Potion effects
- Entity name
- Whether the entity is a baby (if applicable)
- Size attribute (for slimes, magma cubes, and phantoms)

**Comment by YouHaveTrouble** [comment]
This would probably require a lot of effort for a little effect. Sorry.
