### ISSUE TITLE
[Bug] "lightning-transforms-entities" disables vanilla transformations regardless of settings

### ISSUE THREAD

**Issue by Keeg-Turner** [PurpurMC/PurpurExtras#38]
When this feature is enabled, villagers no longer transform into witches and pigs no longer transform into zombified piglins regardless of whether their entries are present in the config or not.

**Comment by YouHaveTrouble** [comment]
fixed in [v1.21.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.21.0)
