### ISSUE TITLE
Add blacklist in Grindstone

### ISSUE THREAD

**Issue by Brand-dev** [PurpurMC/PurpurExtras#43]
### The idea/problem for your feature request.

Hello, it would be nice to be able to blacklist some enchantments with the grindstone option

### Describe the solution you'd like.

Blacklist:
- Mending

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by TheRealRyGuy** [comment]
Blacklist enchantments that don't get removed by the grindstone? Blacklist them so they can't be put into the grindstone? Confused
