### ISSUE TITLE
[Feature Request] Anvil dropping on a chest cart or hopper cart will split it into the 2 separate pieces

### ISSUE THREAD

**Issue by RhythmicSys** [PurpurMC/PurpurExtras#45]
### The idea/problem for your feature request.

Recently minecraft changed chestcarts and hoppercarts to drop as a single item when you break them, which is alright for most things, but there's no way to separate them when you'd like to (looting mineshafts, usually)

### Describe the solution you'd like.

Dropping an anvil on top of the chest/hopper minecart to split it into the 2 items seems like a reasonably logical way to break it in two. Alternatively dropping the minecart entity onto pointed dripstone.

### Describe alternatives you've considered.

I would usually just add a crafting recipe for something like this, but there isn't a way to do it that isn't really convoluted, since it would be resulting in 2 items.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
Added in [v1.24.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.24.0)
