### ISSUE TITLE
Suicide squids

### ISSUE THREAD

**Issue by Nour61** [PurpurMC/PurpurExtras#48]
### The idea/problem for your feature request.

I'm trying to make my world harder for players and I think this would be a good idea alongside with the general theme of squids with Purpur.

### Describe the solution you'd like.

Whenever a player gets in the area of a squid, the squid will swim towards the player and explode. Configurable speed perhaps when the squid detects you.

### Describe alternatives you've considered.

I haven't found any but ChatGPT wrote some small code that seems to work. However it would be a good addition to PurpurExtras.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by TheRealRyGuy** [comment]
Would require a ton of hacky NMS that'd make version updating a pain afaik, not sure if that's desirable

**Comment by YouHaveTrouble** [comment]
> Would require a ton of hacky NMS that'd make version updating a pain afaik, not sure if that's desirable

It's not, but I believe this would be possible with paper's mob goal api

**Comment by TheRealRyGuy** [comment]
mfw had no idea paper had a mob goal api until 30 minutes ago
