### ISSUE TITLE
[Feature Request] Mansion only totem drops

### ISSUE THREAD

**Issue by 1ByteBit** [PurpurMC/PurpurExtras#49]
### The idea/problem for your feature request.

Totem farms (like many other farms) take away from the game itself, can cause lag, and make the item (Totems) nearly meaningless. Basically every totem farm uses raids as a mean of obtaining totems

### Describe the solution you'd like.

An option which when enabled will prevent raid-based evokers from dropping totems upon death, and/or allow changing the drop chance

### Describe alternatives you've considered.

Datapacks: I don't believe it'd be possible to detect if an evoker is from a raid, at least not efficiently without any issues
Purpur Itself: I was told it'd be better as a plugin/Purpur Extras

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
complete in 1.28.0
