### ISSUE TITLE
[Feature Request] Craft Honeycomb from Honeycomb Blocks

### ISSUE THREAD

**Issue by LichLord91** [PurpurMC/PurpurExtras#51]
### The idea/problem for your feature request.

I'd like to get honeycomb back from honeycomb blocks. Really helps with bee farms to back them up to blocks. Surprised Mojang didn't do this like they do with Honey blocks.

### Describe the solution you'd like.

Add crafting recipe to turn Honeycomb blocks into honeycomb items.

### Describe alternatives you've considered.

n/a

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by Encode42** [comment]
This is *much* better as a data pack. Crafting recipes are data-driven, which data packs can modify.

Here's a recipe generated by [a recipe helper](https://crafting.thedestruc7i0n.ca/):
```json
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "#"
    ],
    "key": {
        "#": {
            "item": "minecraft:honeycomb_block"
        }
    },
    "result": {
        "item": "minecraft:honeycomb",
        "count": 4
    }
}
```

**Comment by LichLord91** [comment]
I try to avoid datapacks if I can, though that may be misguided info on potential performance issues with them, unsure.

Is adding it to this plugin a potential performance issue?

Just curious and thanks for linking/explaining , I'll add that site to my bookmarks!

**Comment by Encode42** [comment]
Data packs that use command functions are laggy! - otherwise they're often the better option. World generation, crafting recipes, and loot tables are all examples of things that are data-driven. Data packs that modify these don't impact performance, and are simply easier than implementing them in plugins.

**Comment by LichLord91** [comment]
Awesome, thanks for the info, i'll give datapacks a shot and keep in mind your passed on knowledge, appreciate it. Got a couple of other feature requests coming in. Is it best to do this per request or should I put one ticket for each one? Don't want to spam if thats annoying/not useful.

**Comment by Encode42** [comment]
One issue per request would be the most organized

**Comment by Encode42** [comment]
Closing due to above discussion
