### ISSUE TITLE
[Feature Request]  Loot Chest Block Protection

### ISSUE THREAD

**Issue by LichLord91** [PurpurMC/PurpurExtras#52]
### The idea/problem for your feature request.

I've recently found this plugin [Vane](https://oddlama.github.io/vane/ ). I feel its got similar vibes to Purpur in vanilla enhancement and thought some features could be ported over here that'd probably be more in line with Purpur vision.

Any way they have a feature that's described as:

> Vane is intended to be used with the replenish-loot option by PaperMC, which replenishes loot in loot-chests after 1-2 realtime days. To make players aware of this, vane prevent them from breaking loot chests accidentally. They can remove the block if desired, but are warned before doing so.

[Vane Code](https://github.com/oddlama/vane)

### Describe the solution you'd like.

I  think in addition to what they do above we could have a second option that does not allow that block to break at all or have a certain permission to do so/being OP.

### Describe alternatives you've considered.

n/a

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
Implemented in [1.26.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.26.0)
