### ISSUE TITLE
[Feature Request]  Run Faster on Grass Paths

### ISSUE THREAD

**Issue by LichLord91** [PurpurMC/PurpurExtras#53]
### The idea/problem for your feature request.

This may be for the PurpurMC server jar proper but be cool to run faster when running on grass paths!

### Describe the solution you'd like.

Here is how Vane does it I believe

https://github.com/oddlama/vane/blob/main/vane-trifles/src/main/java/org/oddlama/vane/trifles/FastWalkingGroup.java
https://github.com/oddlama/vane/blob/main/vane-trifles/src/main/java/org/oddlama/vane/trifles/FastWalkingListener.java

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
Implemented in [v1.25.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.25.0)
