### ISSUE TITLE
[Feature Request] Unlock All Recipes

### ISSUE THREAD

**Issue by LichLord91** [PurpurMC/PurpurExtras#54]
### The idea/problem for your feature request.

Many players find it annoying that you have to find recipes before they are shown in your recipe book. Be nice if we can unlock all recipes for a player when they first join a server.

### Describe the solution you'd like.

1. On join automatically get all recipes (perhaps tied with permission group)
2. Make a command that players can run to do this. (configurable true/false and/or permission group)

### Describe alternatives you've considered.

I understand there's a in game command you can do this with. Currently I used a command block that users could press to do this but be nice to have a user command or automatic way to do it. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by BillyGalbreath** [comment]
You know, there is a Discord you can join or a Discussions tab here on GitHub you can use to talk about these feature requests instead of creating useless issue tickets.

**Comment by Encode42** [comment]
(this repository doesn't have discussions set up, billy)

**Comment by BillyGalbreath** [comment]
Oh, I thought this was the Purpur repo :3 My bad lol

**Comment by YouHaveTrouble** [comment]
Implemented in [v1.25.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.25.0)
