### ISSUE TITLE
[Feature Request] Ability to create suspicious sand or gravel

### ISSUE THREAD

**Issue by RhythmicSys** [PurpurMC/PurpurExtras#59]
### The idea/problem for your feature request.

There is no way to  make suspicious gravel

### Describe the solution you'd like.

I think it'd be cool for there to be a way to make suspicious gravel, maybe by shift-right-click-ing an item on gravel, and then it inserts the item in the gravel, or using a hopper to insert it

(Idea stolen from Grian's stream)

### Describe alternatives you've considered.

Possibly a crafting recipe, but that seems less fun

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
Implemented id [1.27.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.27.0)
