### ISSUE TITLE
RamBar and TpsBar

### ISSUE THREAD

**Issue by iTakinn** [PurpurMC/PurpurExtras#67]
### The idea/problem for your feature request.

the /rambar and /tpsbar commands as in the purpur software, I'm running another software and it doesn't have these two essential items

### Describe the solution you'd like.

top line already describes

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
We do not want to duplicate features among our software, sorry, not happening.
