### ISSUE TITLE
[Feature Request] Permissions for opening iron doors/trapdoors with a hand.

### ISSUE THREAD

**Issue by VonSparq** [PurpurMC/PurpurExtras#68]
### The idea/problem for your feature request.

The open-iron-doors-with-hand and open-iron-trapdoors-with-hand tweaks work for everyone once enabled.

### Describe the solution you'd like.

I want players to be able to open iron doors and trapdoors with a hand only if they have a permission to do so. I'd love it if each tweak could have a separate permission.

### Describe alternatives you've considered.

I currently use a plugin called Doors Reloaded for opening iron doors with a hand, it does have a permission check but it doesn't support iron trapdoors.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

### Anything Else?

Thank you very much for creating and maintaining this amazing plugin, much love <3!

**Comment by YouHaveTrouble** [comment]
added in a5f3d36f7ef3ece2e93a13dca3a7fc56b16cfabf
