### ISSUE TITLE
 The loot chest is destroyed by explosives

### ISSUE THREAD

**Issue by jd07159** [PurpurMC/PurpurExtras#77]
### Spark link

https://spark.lucko.me/maIyHUKhWX

### Expected behavior

The loot chest must not be destroyed.

### Observed/Actual behavior

 The loot chest is destroyed by explosives

### Steps/models to reproduce

Turn on the don't allow breaking of blocks with loot tables config option

1 Place an explosive block.
2 Detonate it.
3 The loot chest will be destroyed.

### PurpurExtras version

PurpurExtras version 1.32.0

### Agreements

- [X] I am running the latest version of PurpurExtras available to download from [modrinth.com/plugin/purpurextras/versions](https://modrinth.com/plugin/purpurextras/versions).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by PurpurExtras.
- [X] I am using the latest or recommended version of Purpur available from [purpurmc.org/downloads](https://purpurmc.org/downloads).

**Comment by jd07159** [comment]
trial spawner must also be included in the protection list because it drops loot necessary to open the safe.

**Comment by YouHaveTrouble** [comment]
> trial spawner must also be included in the protection list because it drops loot necessary to open the safe.

I'm not sure if protecting spawners is within the scope of this setting. Perhaps as a separate protect-spawners setting, since spawners technically anre not lootable blocks nor they can regenerate loot

**Comment by jd07159** [comment]
i see, so is it possible to fix loot boxes being destroyed by explosions?

**Comment by YouHaveTrouble** [comment]
Yeah, I'll try to find some time today after work

**Comment by jd07159** [comment]
Thank you

**Comment by YouHaveTrouble** [comment]
additional option added in [1.33.0](https://github.com/PurpurMC/PurpurExtras/releases/tag/v1.33.0)
