### ISSUE TITLE
[Feature Request] spawner-protect

### ISSUE THREAD

**Issue by Qui143** [PurpurMC/PurpurExtras#78]
### The idea/problem for your feature request.

There is a reason to protect the spawner now. Since rewards are given from the trial spawner, I believe we need an option to protect the spawner.

### Describe the solution you'd like.

Spawners can be set to not be destroyed

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported PurpurExtras version.

**Comment by YouHaveTrouble** [comment]
added in 1.34.0
