### ISSUE TITLE
Failed to load module SpawnersProtectionModule

### ISSUE THREAD

**Issue by jd07159** [PurpurMC/PurpurExtras#80]
### Spark link

https://spark.lucko.me/tHfyRFWPrR

### Expected behavior

spawner protect

### Observed/Actual behavior

It cannot be added to the configuration or loaded.
![WindowsTerminal_JyFwML0FHh](https://github.com/user-attachments/assets/6f61889b-47c0-4d9f-b161-7896b34dd553)
Also, when you reload the plugin, this message appears.

### Steps/models to reproduce

I think this bug needs to be fixed.

### PurpurExtras version

PurpurExtras version 1.34.0

### Agreements

- [X] I am running the latest version of PurpurExtras available to download from [modrinth.com/plugin/purpurextras/versions](https://modrinth.com/plugin/purpurextras/versions).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by PurpurExtras.
- [X] I am using the latest or recommended version of Purpur available from [purpurmc.org/downloads](https://purpurmc.org/downloads).

**Comment by YouHaveTrouble** [comment]
fixed in 1.34.1
