### ISSUE TITLE
spawners cannot be destroyed, but The trial spanwer is destroyed.

### ISSUE THREAD

**Issue by jd07159** [PurpurMC/PurpurExtras#81]
### Spark link

https://spark.lucko.me/1UQuvGCpUf

### Expected behavior

trial spawner must not be destroyed

### Observed/Actual behavior

trial spawner is destroyed.

### Steps/models to reproduce

https://github.com/user-attachments/assets/d356825b-daa6-46af-b0b2-bcf54c9d2f41

### PurpurExtras version

PurpurExtras version 1.34.1

### Agreements

- [X] I am running the latest version of PurpurExtras available to download from [modrinth.com/plugin/purpurextras/versions](https://modrinth.com/plugin/purpurextras/versions).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by PurpurExtras.
- [X] I am using the latest or recommended version of Purpur available from [purpurmc.org/downloads](https://purpurmc.org/downloads).

**Comment by YouHaveTrouble** [comment]
Fix merged and live in 1.34.2
